### PR TITLE
Update README: freenode -> libera.chat

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-community/community-topics/issues/19

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
README.md

### CODE REVIEW

**Comment by Andersson007** [comment]
@ssbarnea If i run flake8 locally, it passes. It fails here on `flake8`

**Review by ssbarnea — APPROVED** [review]

**Comment by aminvakil** [comment]
FWIW `flake8 plugins/filter/molecule_core.py` passes fine for me too.

**Review by aminvakil — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
@ssbarnea @aminvakil thanks for reviewing and fixing the lint issues!

**Pull request merged**
